//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyBillsWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BillsEntities : DbContext
    {
        public BillsEntities()
            : base("name=BillsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonthlyBill> MonthlyBills { get; set; }
        public virtual DbSet<transactionsupdateNew> transactionsupdateNews { get; set; }
        public virtual DbSet<WeeklyBill> WeeklyBills { get; set; }
    }
}
